version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $ECR_REGION | docker login
        --username AWS --password-stdin $ECR_REPO
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t ids-app .
      - docker tag ids-app:latest $ECR_REPO:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push $ECR_REPO:latest
      - echo Writing image definitions file...
      - printf '[{"name":"ids-app","imageUri":"%s"}]' $ECR_REPO:latest >
        imagedefinitions.json
artifacts:
  files: imagedefinitions.json